# Generated by Django 5.0 on 2023-12-14 23:27

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pastor', models.CharField(max_length=255)),
                ('s_pastor', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(max_length=255)),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='ZA')),
                ('history', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
